version: '3'

networks:
  first-network:
    driver: bridge
  second-network:
    driver: bridge

services:

  bdd:
    image: mariadb:latest
    container_name: bdd
    restart: always
    volumes:
      - ./maria-game-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: db_words_game
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    networks:
      - first-network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - first-network

  service_api:
    image: cocor31/game-api:main
    container_name: service_api
    extra_hosts:
      # for linux hosts since version 20.10
      - host.docker.internal:host-gateway
    restart: always
    environment:
      MARIADB_HOST: bdd
      MARIADB_DATABASE: db_words_game
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor

    ports:
      - 5000:5000
    links:
      - bdd
    networks:
      - first-network

  service_gamemanager:
    image: cocor31/game-manager:main
    container_name: service_gamemanager
    restart: always
    env_file: ./.env
    environment:
      - API_URL=service_api
      - API_PORT=5000
      - MONGO_DB_STRING=${MONGO_DB_STRING}
    ports:
      - 5001:5001
    networks:
      - first-network

  service_front:
    image: cocor31/game-front:main
    container_name: service_front
    restart: always
    ports:
      - 80:80
    depends_on:
      service_api:
        condition: service_started
    networks:
      - first-network
