version: '3'

# networks:
#   testNetwork:

networks:
  first-network:
    driver: bridge
  second-network:
    driver: bridge

services:

  bdd:
    image: mariadb:latest
    container_name: bdd
    restart: always
    volumes:
      - game-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: db_words_game
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    networks:
      - first-network

  service_api:
    build: ./api
    container_name: service_api
    extra_hosts:
      # for linux hosts since version 20.10
      - host.docker.internal:host-gateway
    restart: always
    # env_file:
    #   - ./api/.env
    environment:
      MARIADB_HOST: bdd
      MARIADB_DATABASE: db_words_game
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor

    # expose:
    #   - "5000"
    ports:
      - 5000:5000
    links:
      - bdd
    networks:
      # - testNetwork
      - first-network

  service_gamemanager:
    build: ./gamemanager
    container_name: service_gamemanager
    restart: always
    environment:
      - FRONT_URL=localhost
      - FRONT_PORT=80
      - API_URL= service_api
      - API_PORT= 5000
    ports:
      - 5001:5001
    # expose:
    #   - 5001
    networks:
      - first-network

  # gateway:
  #   build: ./gateway
  #   container_name: gateway
  #   restart: always
  #   environment:
  #     - URL_API=api2
  #     - URL_GAMEMANAGER=gamemanager
  #   ports:
  #     - 4000:4000
  #   networks:
  #     - first-network

  # proxy:
  #   image: nginx:latest
  #   container_name: proxy
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - front2
  #     - api2
  #     - gamemanager
  #   networks:
  #     - first-network

  service_front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: service_front
    # environment:
    # - VITE_SERVER_URL=host.docker.internal
    # - VITE_SERVER_URL=10.10.10.10
    # - VITE_GAMEMANAGER_PORT=5001
    # - VITE_API_PORT=5000
    ports:
      - 80:80
    # ports:
    #   - 80:80
    links:
      - service_gamemanager
      - service_api
    networks:
      # - testNetwork
      - first-network
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./front/dist:/var/www/front-end
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     api2:
  #       condition: service_started
  #   networks:
  #     # - testNetwork
  #     - second-network

volumes:
  game-db:


