name: Integration continue

on:
    push:
        branches: 
            - main
            - dev
    pull_request:
        branches: ["main"]

jobs:
    testApi:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: api

        services:
            mariadb:
                image: mariadb:latest
                env:
                    MARIADB_ROOT_PASSWORD: toor
                    MARIADB_DATABASE: test
                    MARIADB_USER: test
                    MARIADB_PASSWORD: test
                ports:
                    - 3306:3306
                options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

        env:
            MARIADB_HOST: 127.0.0.1
            # DB_NAME: test
            # DB_USER: test
            # DB_PASS: test
            MARIADB_PORT: 3306
            MARIADB_DATABASE: test
            # MARIADB_ROOT_PASSWORD: toor
            MARIADB_USER: test
            MARIADB_PASSWORD: test

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Check database connection
              run: |
                sudo apt-get install -y mysql-client
                mysql --host 127.0.0.1 --port 3306 -u root -ptoor -e "SHOW DATABASES"

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 18.x

            - name: Install Dependencies
              run: npm i

            # - name: Init database
            #   run: echo Test Done

            - name: Run API Test
              run: npm run test
              
    
    deploy:
        needs: [testApi]
        if: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev') }}      
        uses: ./.github/workflows/cd.yml
        secrets: inherit
        